name: qemu-minimal
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.wordlist.txt'
      - '.spellcheck.yaml'

jobs:
  spell-check:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v4.1.1
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@v0
